<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE sales_doc [
        <!ELEMENT sales_doc (sale_record)*>
        <!ELEMENT sale_record (id,first_name,last_name,sales,state,department)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT first_name (#PCDATA)>
        <!ELEMENT last_name (#PCDATA)>
        <!ELEMENT sales (#PCDATA)>
        <!ELEMENT state (#PCDATA)>
        <!ELEMENT department (#PCDATA)>
        ]>
<sales_doc>
    <sale_record>
        <id>1</id>
        <first_name>Ashla</first_name>
        <last_name>Secretan</last_name>
        <sales>9461.42</sales>
        <state>California</state>
        <department>Health</department>
    </sale_record>
    <sale_record>
        <id>2</id>
        <first_name>Conny</first_name>
        <last_name>Sadry</last_name>
        <sales>5266.05</sales>
        <state>Tennessee</state>
        <department>Computers</department>
    </sale_record>
    <sale_record>
        <id>3</id>
        <first_name>Hermia</first_name>
        <last_name>Arnowicz</last_name>
        <sales>6807.11</sales>
        <state>Nebraska</state>
        <department>Sports</department>
    </sale_record>
    <sale_record>
        <id>4</id>
        <first_name>Kissiah</first_name>
        <last_name>Kennifick</last_name>
        <sales>6852.69</sales>
        <state>Florida</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>5</id>
        <first_name>Jacquenette</first_name>
        <last_name>Attarge</last_name>
        <sales>4634.62</sales>
        <state>District of Columbia</state>
        <department>Movies</department>
    </sale_record>
    <sale_record>
        <id>6</id>
        <first_name>Sophey</first_name>
        <last_name>MacCracken</last_name>
        <sales>4736.67</sales>
        <state>Florida</state>
        <department>Electronics</department>
    </sale_record>
    <sale_record>
        <id>7</id>
        <first_name>Clerissa</first_name>
        <last_name>Groucutt</last_name>
        <sales>6905.08</sales>
        <state>Iowa</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>8</id>
        <first_name>Norton</first_name>
        <last_name>Currey</last_name>
        <sales>3845.4</sales>
        <state>District of Columbia</state>
        <department>Garden</department>
    </sale_record>
    <sale_record>
        <id>9</id>
        <first_name>Caye</first_name>
        <last_name>Iskowicz</last_name>
        <sales>2969.36</sales>
        <state>South Carolina</state>
        <department>Garden</department>
    </sale_record>
    <sale_record>
        <id>10</id>
        <first_name>Billy</first_name>
        <last_name>Pavlenkov</last_name>
        <sales>7731.69</sales>
        <state>Texas</state>
        <department>Garden</department>
    </sale_record>
    <sale_record>
        <id>11</id>
        <first_name>Shae</first_name>
        <last_name>Edinborough</last_name>
        <sales>6324.77</sales>
        <state>California</state>
        <department>Toys</department>
    </sale_record>
    <sale_record>
        <id>12</id>
        <first_name>Leonard</first_name>
        <last_name>Frankton</last_name>
        <sales>5800.66</sales>
        <state>Ohio</state>
        <department>Home</department>
    </sale_record>
    <sale_record>
        <id>13</id>
        <first_name>Abra</first_name>
        <last_name>Maha</last_name>
        <sales>4177.19</sales>
        <state>Washington</state>
        <department>Books</department>
    </sale_record>
    <sale_record>
        <id>14</id>
        <first_name>Gilberta</first_name>
        <last_name>Livens</last_name>
        <sales>2681.05</sales>
        <state>Florida</state>
        <department>Industrial</department>
    </sale_record>
    <sale_record>
        <id>15</id>
        <first_name>Robby</first_name>
        <last_name>Wince</last_name>
        <sales>2307.23</sales>
        <state>Indiana</state>
        <department>Electronics</department>
    </sale_record>
    <sale_record>
        <id>16</id>
        <first_name>Ethel</first_name>
        <last_name>Capron</last_name>
        <sales>8676.91</sales>
        <state>Texas</state>
        <department>Movies</department>
    </sale_record>
    <sale_record>
        <id>17</id>
        <first_name>Rosie</first_name>
        <last_name>Denholm</last_name>
        <sales>9929.9</sales>
        <state>Georgia</state>
        <department>Automotive</department>
    </sale_record>
    <sale_record>
        <id>18</id>
        <first_name>Darnell</first_name>
        <last_name>Millthorpe</last_name>
        <sales>7247.74</sales>
        <state>Arizona</state>
        <department>Sports</department>
    </sale_record>
    <sale_record>
        <id>19</id>
        <first_name>Cyb</first_name>
        <last_name>Duggon</last_name>
        <sales>3592.27</sales>
        <state>Tennessee</state>
        <department>Movies</department>
    </sale_record>
    <sale_record>
        <id>20</id>
        <first_name>Frayda</first_name>
        <last_name>Overthrow</last_name>
        <sales>4773.19</sales>
        <state>California</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>21</id>
        <first_name>Maitilde</first_name>
        <last_name>Rame</last_name>
        <sales>7785.01</sales>
        <state>Texas</state>
        <department>Books</department>
    </sale_record>
    <sale_record>
        <id>22</id>
        <first_name>Heinrick</first_name>
        <last_name>Karpmann</last_name>
        <sales>5009.03</sales>
        <state>New York</state>
        <department>Automotive</department>
    </sale_record>
    <sale_record>
        <id>23</id>
        <first_name>Rance</first_name>
        <last_name>Brabant</last_name>
        <sales>6248.19</sales>
        <state>New York</state>
        <department>Home</department>
    </sale_record>
    <sale_record>
        <id>24</id>
        <first_name>Nicola</first_name>
        <last_name>Hubbuck</last_name>
        <sales>7752.73</sales>
        <state>Kentucky</state>
        <department>Baby</department>
    </sale_record>
    <sale_record>
        <id>25</id>
        <first_name>Stanwood</first_name>
        <last_name>Stading</last_name>
        <sales>3326.15</sales>
        <state>Louisiana</state>
        <department>Health</department>
    </sale_record>
    <sale_record>
        <id>26</id>
        <first_name>Jeane</first_name>
        <last_name>Broyd</last_name>
        <sales>3711.06</sales>
        <state>Maryland</state>
        <department>Outdoors</department>
    </sale_record>
    <sale_record>
        <id>27</id>
        <first_name>Walther</first_name>
        <last_name>Blazdell</last_name>
        <sales>1800.19</sales>
        <state>Maryland</state>
        <department>Books</department>
    </sale_record>
    <sale_record>
        <id>28</id>
        <first_name>Heida</first_name>
        <last_name>Cholmondeley</last_name>
        <sales>5211.09</sales>
        <state>Virginia</state>
        <department>Garden</department>
    </sale_record>
    <sale_record>
        <id>29</id>
        <first_name>Onofredo</first_name>
        <last_name>Rodway</last_name>
        <sales>4176.25</sales>
        <state>California</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>30</id>
        <first_name>Damien</first_name>
        <last_name>Fraczek</last_name>
        <sales>3882.41</sales>
        <state>Florida</state>
        <department>Sports</department>
    </sale_record>
    <sale_record>
        <id>31</id>
        <first_name>Cicily</first_name>
        <last_name>Longbottom</last_name>
        <sales>1487.03</sales>
        <state>New York</state>
        <department>Jewelry</department>
    </sale_record>
    <sale_record>
        <id>32</id>
        <first_name>Nathanael</first_name>
        <last_name>Cammish</last_name>
        <sales>5005.73</sales>
        <state>California</state>
        <department>Tools</department>
    </sale_record>
    <sale_record>
        <id>33</id>
        <first_name>Daryle</first_name>
        <last_name>Bushrod</last_name>
        <sales>2093.72</sales>
        <state>Illinois</state>
        <department>Industrial</department>
    </sale_record>
    <sale_record>
        <id>34</id>
        <first_name>Darla</first_name>
        <last_name>Crannage</last_name>
        <sales>2756.25</sales>
        <state>South Carolina</state>
        <department>Tools</department>
    </sale_record>
    <sale_record>
        <id>35</id>
        <first_name>Nina</first_name>
        <last_name>Carruthers</last_name>
        <sales>9380.85</sales>
        <state>California</state>
        <department>Toys</department>
    </sale_record>
    <sale_record>
        <id>36</id>
        <first_name>Dosi</first_name>
        <last_name>Birdis</last_name>
        <sales>3256.74</sales>
        <state>California</state>
        <department>Garden</department>
    </sale_record>
    <sale_record>
        <id>37</id>
        <first_name>Coletta</first_name>
        <last_name>Tackett</last_name>
        <sales>1651.85</sales>
        <state>Ohio</state>
        <department>Electronics</department>
    </sale_record>
    <sale_record>
        <id>38</id>
        <first_name>Livvie</first_name>
        <last_name>Ughetti</last_name>
        <sales>2566.47</sales>
        <state>South Dakota</state>
        <department>Tools</department>
    </sale_record>
    <sale_record>
        <id>39</id>
        <first_name>Leticia</first_name>
        <last_name>Iacobini</last_name>
        <sales>7623.81</sales>
        <state>District of Columbia</state>
        <department>Health</department>
    </sale_record>
    <sale_record>
        <id>40</id>
        <first_name>Milly</first_name>
        <last_name>Danielczyk</last_name>
        <sales>5288.74</sales>
        <state>Colorado</state>
        <department>Kids</department>
    </sale_record>
    <sale_record>
        <id>41</id>
        <first_name>Jere</first_name>
        <last_name>D'Orsay</last_name>
        <sales>8445.92</sales>
        <state>Texas</state>
        <department>Beauty</department>
    </sale_record>
    <sale_record>
        <id>42</id>
        <first_name>Murry</first_name>
        <last_name>Di Ruggero</last_name>
        <sales>6678.98</sales>
        <state>California</state>
        <department>Garden</department>
    </sale_record>
    <sale_record>
        <id>43</id>
        <first_name>Umeko</first_name>
        <last_name>Eadmead</last_name>
        <sales>8829.9</sales>
        <state>Ohio</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>44</id>
        <first_name>Iseabal</first_name>
        <last_name>Heisham</last_name>
        <sales>5993.5</sales>
        <state>New York</state>
        <department>Outdoors</department>
    </sale_record>
    <sale_record>
        <id>45</id>
        <first_name>Jenni</first_name>
        <last_name>Huonic</last_name>
        <sales>8526.62</sales>
        <state>Florida</state>
        <department>Outdoors</department>
    </sale_record>
    <sale_record>
        <id>46</id>
        <first_name>Douglass</first_name>
        <last_name>Stenners</last_name>
        <sales>5837.08</sales>
        <state>Washington</state>
        <department>Kids</department>
    </sale_record>
    <sale_record>
        <id>47</id>
        <first_name>Josie</first_name>
        <last_name>O'Sheilds</last_name>
        <sales>7702.38</sales>
        <state>California</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>48</id>
        <first_name>Ulysses</first_name>
        <last_name>Hanster</last_name>
        <sales>6761.24</sales>
        <state>California</state>
        <department>Books</department>
    </sale_record>
    <sale_record>
        <id>49</id>
        <first_name>Quintin</first_name>
        <last_name>Featherstone</last_name>
        <sales>8174.45</sales>
        <state>Oklahoma</state>
        <department>Games</department>
    </sale_record>
    <sale_record>
        <id>50</id>
        <first_name>Edin</first_name>
        <last_name>Isack</last_name>
        <sales>4593.69</sales>
        <state>Utah</state>
        <department>Games</department>
    </sale_record>
    <sale_record>
        <id>51</id>
        <first_name>Truda</first_name>
        <last_name>Ainsby</last_name>
        <sales>5472.92</sales>
        <state>Florida</state>
        <department>Movies</department>
    </sale_record>
    <sale_record>
        <id>52</id>
        <first_name>Courtney</first_name>
        <last_name>Kisbey</last_name>
        <sales>7687.11</sales>
        <state>Ohio</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>53</id>
        <first_name>Chlo</first_name>
        <last_name>Annand</last_name>
        <sales>4921.7</sales>
        <state>Kentucky</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>54</id>
        <first_name>Orsa</first_name>
        <last_name>Yellowlee</last_name>
        <sales>5192.57</sales>
        <state>North Carolina</state>
        <department>Garden</department>
    </sale_record>
    <sale_record>
        <id>55</id>
        <first_name>Dev</first_name>
        <last_name>Dimsdale</last_name>
        <sales>6847.6</sales>
        <state>New York</state>
        <department>Industrial</department>
    </sale_record>
    <sale_record>
        <id>56</id>
        <first_name>Aveline</first_name>
        <last_name>Beecker</last_name>
        <sales>6569.42</sales>
        <state>Michigan</state>
        <department>Shoes</department>
    </sale_record>
    <sale_record>
        <id>57</id>
        <first_name>Gaspar</first_name>
        <last_name>Castellan</last_name>
        <sales>6809.27</sales>
        <state>New York</state>
        <department>Toys</department>
    </sale_record>
    <sale_record>
        <id>58</id>
        <first_name>Vivianne</first_name>
        <last_name>Kenton</last_name>
        <sales>4306.76</sales>
        <state>District of Columbia</state>
        <department>Automotive</department>
    </sale_record>
    <sale_record>
        <id>59</id>
        <first_name>Christye</first_name>
        <last_name>Daley</last_name>
        <sales>6205.67</sales>
        <state>Texas</state>
        <department>Books</department>
    </sale_record>
    <sale_record>
        <id>60</id>
        <first_name>Adolpho</first_name>
        <last_name>Pavolillo</last_name>
        <sales>9612.99</sales>
        <state>Colorado</state>
        <department>Outdoors</department>
    </sale_record>
    <sale_record>
        <id>61</id>
        <first_name>Aurelea</first_name>
        <last_name>Holbury</last_name>
        <sales>8991.91</sales>
        <state>Nebraska</state>
        <department>Home</department>
    </sale_record>
    <sale_record>
        <id>62</id>
        <first_name>Pasquale</first_name>
        <last_name>Ribbens</last_name>
        <sales>9725.53</sales>
        <state>Florida</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>63</id>
        <first_name>Jecho</first_name>
        <last_name>Rubinovitsch</last_name>
        <sales>8104.04</sales>
        <state>Florida</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>64</id>
        <first_name>Jeffy</first_name>
        <last_name>Peacop</last_name>
        <sales>6052.05</sales>
        <state>Hawaii</state>
        <department>Books</department>
    </sale_record>
    <sale_record>
        <id>65</id>
        <first_name>Bibi</first_name>
        <last_name>Cheeseman</last_name>
        <sales>3724.89</sales>
        <state>Arizona</state>
        <department>Jewelry</department>
    </sale_record>
    <sale_record>
        <id>66</id>
        <first_name>Manon</first_name>
        <last_name>Alldread</last_name>
        <sales>7147.92</sales>
        <state>Missouri</state>
        <department>Grocery</department>
    </sale_record>
    <sale_record>
        <id>67</id>
        <first_name>Dana</first_name>
        <last_name>Dahlback</last_name>
        <sales>2485.5</sales>
        <state>Connecticut</state>
        <department>Tools</department>
    </sale_record>
    <sale_record>
        <id>68</id>
        <first_name>Myrlene</first_name>
        <last_name>Sherrock</last_name>
        <sales>8573.09</sales>
        <state>Montana</state>
        <department>Automotive</department>
    </sale_record>
    <sale_record>
        <id>69</id>
        <first_name>Anastasia</first_name>
        <last_name>Elleton</last_name>
        <sales>7689.15</sales>
        <state>North Carolina</state>
        <department>Books</department>
    </sale_record>
    <sale_record>
        <id>70</id>
        <first_name>Carly</first_name>
        <last_name>Gerred</last_name>
        <sales>3791.35</sales>
        <state>California</state>
        <department>Sports</department>
    </sale_record>
    <sale_record>
        <id>71</id>
        <first_name>Lyn</first_name>
        <last_name>Windross</last_name>
        <sales>2199.09</sales>
        <state>Pennsylvania</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>72</id>
        <first_name>Dionne</first_name>
        <last_name>Stienham</last_name>
        <sales>9310.75</sales>
        <state>Texas</state>
        <department>Computers</department>
    </sale_record>
    <sale_record>
        <id>73</id>
        <first_name>Mavis</first_name>
        <last_name>Dafter</last_name>
        <sales>1550.36</sales>
        <state>South Carolina</state>
        <department>Industrial</department>
    </sale_record>
    <sale_record>
        <id>74</id>
        <first_name>Laurella</first_name>
        <last_name>Whenham</last_name>
        <sales>7311.89</sales>
        <state>Michigan</state>
        <department>Movies</department>
    </sale_record>
    <sale_record>
        <id>75</id>
        <first_name>Friedrich</first_name>
        <last_name>Rizzi</last_name>
        <sales>4934.06</sales>
        <state>Texas</state>
        <department>Beauty</department>
    </sale_record>
    <sale_record>
        <id>76</id>
        <first_name>Sheryl</first_name>
        <last_name>Scobbie</last_name>
        <sales>9369.67</sales>
        <state>Iowa</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>77</id>
        <first_name>Kimbell</first_name>
        <last_name>Gransden</last_name>
        <sales>4719.5</sales>
        <state>Minnesota</state>
        <department>Toys</department>
    </sale_record>
    <sale_record>
        <id>78</id>
        <first_name>Christian</first_name>
        <last_name>Corlett</last_name>
        <sales>7591.99</sales>
        <state>Kentucky</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>79</id>
        <first_name>Rochella</first_name>
        <last_name>Pealing</last_name>
        <sales>4899.19</sales>
        <state>Oklahoma</state>
        <department>Health</department>
    </sale_record>
    <sale_record>
        <id>80</id>
        <first_name>Nanny</first_name>
        <last_name>Rouzet</last_name>
        <sales>4354.07</sales>
        <state>Colorado</state>
        <department>Grocery</department>
    </sale_record>
    <sale_record>
        <id>81</id>
        <first_name>Elliott</first_name>
        <last_name>Grimley</last_name>
        <sales>4475.29</sales>
        <state>Nevada</state>
        <department>Movies</department>
    </sale_record>
    <sale_record>
        <id>82</id>
        <first_name>Joyous</first_name>
        <last_name>Old</last_name>
        <sales>6768.55</sales>
        <state>California</state>
        <department>Games</department>
    </sale_record>
    <sale_record>
        <id>83</id>
        <first_name>Marlene</first_name>
        <last_name>Eric</last_name>
        <sales>1466.54</sales>
        <state>Utah</state>
        <department>Games</department>
    </sale_record>
    <sale_record>
        <id>84</id>
        <first_name>Erny</first_name>
        <last_name>Liddiard</last_name>
        <sales>2888.33</sales>
        <state>Alabama</state>
        <department>Electronics</department>
    </sale_record>
    <sale_record>
        <id>85</id>
        <first_name>Raffarty</first_name>
        <last_name>Bevans</last_name>
        <sales>6239.01</sales>
        <state>District of Columbia</state>
        <department>Health</department>
    </sale_record>
    <sale_record>
        <id>86</id>
        <first_name>Leoine</first_name>
        <last_name>Shelley</last_name>
        <sales>5089.99</sales>
        <state>California</state>
        <department>Beauty</department>
    </sale_record>
    <sale_record>
        <id>87</id>
        <first_name>Ginni</first_name>
        <last_name>Philcock</last_name>
        <sales>8731.55</sales>
        <state>California</state>
        <department>Beauty</department>
    </sale_record>
    <sale_record>
        <id>88</id>
        <first_name>Jamill</first_name>
        <last_name>Bergeau</last_name>
        <sales>1704.09</sales>
        <state>Oregon</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>89</id>
        <first_name>Dorita</first_name>
        <last_name>Mancktelow</last_name>
        <sales>3567.4</sales>
        <state>Hawaii</state>
        <department>Toys</department>
    </sale_record>
    <sale_record>
        <id>90</id>
        <first_name>Doll</first_name>
        <last_name>Hadlow</last_name>
        <sales>7072.84</sales>
        <state>Maryland</state>
        <department>Tools</department>
    </sale_record>
    <sale_record>
        <id>91</id>
        <first_name>Wainwright</first_name>
        <last_name>De Few</last_name>
        <sales>8988.38</sales>
        <state>Connecticut</state>
        <department>Jewelry</department>
    </sale_record>
    <sale_record>
        <id>92</id>
        <first_name>Tomasine</first_name>
        <last_name>Ferraraccio</last_name>
        <sales>3492.02</sales>
        <state>Georgia</state>
        <department>Outdoors</department>
    </sale_record>
    <sale_record>
        <id>93</id>
        <first_name>Salli</first_name>
        <last_name>Groucock</last_name>
        <sales>2726.4</sales>
        <state>Georgia</state>
        <department>Electronics</department>
    </sale_record>
    <sale_record>
        <id>94</id>
        <first_name>Annmaria</first_name>
        <last_name>Akaster</last_name>
        <sales>5283.11</sales>
        <state>California</state>
        <department>Jewelry</department>
    </sale_record>
    <sale_record>
        <id>95</id>
        <first_name>Dot</first_name>
        <last_name>Le Page</last_name>
        <sales>7453.28</sales>
        <state>Wisconsin</state>
        <department>Home</department>
    </sale_record>
    <sale_record>
        <id>96</id>
        <first_name>Margeaux</first_name>
        <last_name>Ganley</last_name>
        <sales>7675.85</sales>
        <state>Georgia</state>
        <department>Sports</department>
    </sale_record>
    <sale_record>
        <id>97</id>
        <first_name>Mikaela</first_name>
        <last_name>Scarse</last_name>
        <sales>5803.26</sales>
        <state>Louisiana</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>98</id>
        <first_name>George</first_name>
        <last_name>Andreev</last_name>
        <sales>8270.74</sales>
        <state>Florida</state>
        <department>Home</department>
    </sale_record>
    <sale_record>
        <id>99</id>
        <first_name>Vaughn</first_name>
        <last_name>Tooze</last_name>
        <sales>5924.49</sales>
        <state>New York</state>
        <department>Computers</department>
    </sale_record>
    <sale_record>
        <id>100</id>
        <first_name>Doll</first_name>
        <last_name>Richardeau</last_name>
        <sales>3682.06</sales>
        <state>Texas</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>101</id>
        <first_name>Andrew</first_name>
        <last_name>Dominguez</last_name>
        <sales>7059.74</sales>
        <state>Washington</state>
        <department>Grocery</department>
    </sale_record>
    <sale_record>
        <id>102</id>
        <first_name>Leland</first_name>
        <last_name>Gummie</last_name>
        <sales>7850.91</sales>
        <state>Nebraska</state>
        <department>Home</department>
    </sale_record>
    <sale_record>
        <id>103</id>
        <first_name>Papagena</first_name>
        <last_name>Jenking</last_name>
        <sales>1584.9</sales>
        <state>Washington</state>
        <department>Games</department>
    </sale_record>
    <sale_record>
        <id>104</id>
        <first_name>Sybila</first_name>
        <last_name>Kuhnke</last_name>
        <sales>4577.17</sales>
        <state>Iowa</state>
        <department>Computers</department>
    </sale_record>
    <sale_record>
        <id>105</id>
        <first_name>Eve</first_name>
        <last_name>Poppleston</last_name>
        <sales>4062.28</sales>
        <state>Indiana</state>
        <department>Beauty</department>
    </sale_record>
    <sale_record>
        <id>106</id>
        <first_name>Doretta</first_name>
        <last_name>Wahlberg</last_name>
        <sales>2260.24</sales>
        <state>Connecticut</state>
        <department>Computers</department>
    </sale_record>
    <sale_record>
        <id>107</id>
        <first_name>Bax</first_name>
        <last_name>Spurden</last_name>
        <sales>9468.02</sales>
        <state>Missouri</state>
        <department>Computers</department>
    </sale_record>
    <sale_record>
        <id>108</id>
        <first_name>Paulo</first_name>
        <last_name>Brookwood</last_name>
        <sales>1408.92</sales>
        <state>Texas</state>
        <department>Games</department>
    </sale_record>
    <sale_record>
        <id>109</id>
        <first_name>Gibbie</first_name>
        <last_name>Pascho</last_name>
        <sales>2567.15</sales>
        <state>Texas</state>
        <department>Industrial</department>
    </sale_record>
    <sale_record>
        <id>110</id>
        <first_name>Alysia</first_name>
        <last_name>Hylands</last_name>
        <sales>2430.99</sales>
        <state>Tennessee</state>
        <department>Music</department>
    </sale_record>
    <sale_record>
        <id>111</id>
        <first_name>Suzie</first_name>
        <last_name>Pendlebery</last_name>
        <sales>5125.7</sales>
        <state>Texas</state>
        <department>Movies</department>
    </sale_record>
    <sale_record>
        <id>112</id>
        <first_name>Kerk</first_name>
        <last_name>Farron</last_name>
        <sales>2174.92</sales>
        <state>Arizona</state>
        <department>Books</department>
    </sale_record>
    <sale_record>
        <id>113</id>
        <first_name>Wallache</first_name>
        <last_name>Truman</last_name>
        <sales>3791.46</sales>
        <state>Ohio</state>
        <department>Industrial</department>
    </sale_record>
    <sale_record>
        <id>114</id>
        <first_name>Sarene</first_name>
        <last_name>McGiffin</last_name>
        <sales>7791.88</sales>
        <state>Texas</state>
        <department>Health</department>
    </sale_record>
    <sale_record>
        <id>115</id>
        <first_name>Shirlee</first_name>
        <last_name>Yanson</last_name>
        <sales>7183.39</sales>
        <state>Indiana</state>
        <department>Shoes</department>
    </sale_record>
    <sale_record>
        <id>116</id>
        <first_name>Gabriella</first_name>
        <last_name>Pergens</last_name>
        <sales>3168.35</sales>
        <state>New York</state>
        <department>Home</department>
    </sale_record>
    <sale_record>
        <id>117</id>
        <first_name>Alexia</first_name>
        <last_name>Tokell</last_name>
        <sales>6365.11</sales>
        <state>Kentucky</state>
        <department>Industrial</department>
    </sale_record>
    <sale_record>
        <id>118</id>
        <first_name>Rosabella</first_name>
        <last_name>Finby</last_name>
        <sales>9719.38</sales>
        <state>Pennsylvania</state>
        <department>Home</department>
    </sale_record>
    <sale_record>
        <id>119</id>
        <first_name>Etta</first_name>
        <last_name>Tanfield</last_name>
        <sales>6667.04</sales>
        <state>Florida</state>
        <department>Movies</department>
    </sale_record>
    <sale_record>
        <id>120</id>
        <first_name>Holli</first_name>
        <last_name>Coxhell</last_name>
        <sales>9646.16</sales>
        <state>Virginia</state>
        <department>Shoes</department>
    </sale_record>
    <sale_record>
        <id>121</id>
        <first_name>Bron</first_name>
        <last_name>Heading</last_name>
        <sales>4570.62</sales>
        <state>North Dakota</state>
        <department>Kids</department>
    </sale_record>
    <sale_record>
        <id>122</id>
        <first_name>Annie</first_name>
        <last_name>Taveriner</last_name>
        <sales>3501.59</sales>
        <state>Tennessee</state>
        <department>Clothing</department>
    </sale_record>
    <sale_record>
        <id>123</id>
        <first_name>Erma</first_name>
        <last_name>Exer</last_name>
        <sales>1629.9</sales>
        <state>Illinois</state>
        <department>Clothing</department>
    </sale_record>